import type { BookingService, ServiceId } from './types'

export const SERVICES: BookingService[] = [
  {
    id: 'open-play',
    label: 'Open Play',
    imgUrl: '/booking/play.jpeg',
    photoUrl: '/booking/play.jpeg',
    desc: 'Drop-in sessions for curious kids of all ages',
    color: 'var(--dt-teal)',
    colorHex: '#00c49a',
    bgClass: 'bg-[#F0FDFB]',
    options: [
      {
        slug: '2-hour-pass',
        label: '2-Hour Pass',
        price: '$12',
        unit: 'per child',
        desc: 'Perfect for spontaneous visits with supervised, open-ended exploration.',
        inclusions: ['2 hours of play access', 'All activity zones', 'Parent lounge access'],
      },
      {
        slug: 'sibling-pass',
        label: 'Sibling Pass',
        price: '$10',
        unit: 'per sibling',
        desc: 'Add siblings at a discounted rate so the full family can join.',
        inclusions: ['Valid with primary pass', 'Same-day shared session', 'All zones included'],
      },
      {
        slug: 'multi-pass',
        label: 'Multi-Pass',
        price: '$50',
        unit: '5 admissions',
        desc: 'Best for frequent visitors who want flexibility and savings.',
        inclusions: ['5 total entries', 'Flexible day/time', 'Priority weekend scheduling'],
        badge: 'Best Value',
      },
      {
        slug: 'monthly-membership',
        label: 'Monthly Membership',
        price: '$45',
        unit: 'per child/month',
        desc: 'Unlimited access with member-only perks for regular families.',
        inclusions: ['Unlimited open play', 'Member discounts', 'Monthly coffee perk'],
      },
    ],
    addons: ['Grip Socks ($3)', 'Snack Pack ($8)', 'Photo Package ($15)'],
    times: ['9:00 AM', '10:00 AM', '11:00 AM', '12:00 PM', '1:00 PM', '2:00 PM', '3:00 PM', '4:00 PM'],
  },
  {
    id: 'private-play',
    label: 'Private Play',
    imgUrl: '/booking/privateplay.jpeg',
    photoUrl: '/booking/privateplay.jpeg',
    desc: 'Reserve the whole space just for your group',
    color: 'var(--dt-primary)',
    colorHex: '#1d7fe5',
    bgClass: 'bg-[#EFF6FF]',
    options: [
      {
        slug: 'party-room',
        label: 'Party Room + Open Play',
        price: '$299',
        unit: 'starting',
        desc: 'Dedicated private room while guests enjoy full open-play access.',
        inclusions: ['Private party room', 'Open play admission', 'Setup + cleanup'],
      },
      {
        slug: 'venue-buyout',
        label: 'Whole Venue Buyout',
        price: '$899',
        unit: 'starting',
        desc: 'Complete exclusive access for uninterrupted celebrations.',
        inclusions: ['Full-venue access', 'Dedicated team', 'Flexible layout'],
        badge: 'Most Exclusive',
      },
      {
        slug: 'meeting-room',
        label: 'Meeting Room Rental',
        price: '$149',
        unit: 'starting',
        desc: 'Workshops, classes, and parent groups in a comfortable space.',
        inclusions: ['Private meeting room', 'Presentation support', 'Optional play add-ons'],
      },
    ],
    addons: ['Catering Package ($150)', 'Decoration Setup ($75)', 'DJ / Music ($100)', 'Photo Booth ($120)'],
    times: ['10:00 AM', '12:00 PM', '2:00 PM', '4:00 PM', '6:00 PM'],
  },
  {
    id: 'camps',
    label: 'Camps',
    imgUrl: '/booking/camp.jpeg',
    photoUrl: '/booking/camp.jpeg',
    desc: 'Structured programs during school breaks',
    color: 'var(--dt-purple)',
    colorHex: '#7c3aed',
    bgClass: 'bg-[#F5F3FF]',
    options: [
      {
        slug: 'summer-camp',
        label: 'Summer Camp',
        price: '$245',
        unit: 'per week',
        desc: 'Multi-week themed activities, group games, and creative stations.',
        inclusions: ['Daily supervised programming', 'Activity materials', 'Outdoor + indoor play'],
      },
      {
        slug: 'winter-camp',
        label: 'Winter Break Camp',
        price: '$215',
        unit: 'per week',
        desc: 'Keep kids active with movement, crafts, and social play.',
        inclusions: ['Winter themed activities', 'Indoor play sessions', 'Daily check-in'],
      },
      {
        slug: 'spring-camp',
        label: 'Spring Break Camp',
        price: '$205',
        unit: 'per week',
        desc: 'Science play, games, and hands-on projects all week.',
        inclusions: ['Project-based activities', 'Team games', 'Supervised free play'],
      },
      {
        slug: 'mlk-day',
        label: 'MLK Day Camp',
        price: '$65',
        unit: 'single day',
        desc: 'Single-day school-break camp with engaging activities.',
        inclusions: ['Full day schedule', 'Creative stations', 'Snack break windows'],
      },
    ],
    addons: ['Lunch Add-on ($10/day)', 'Extended Care ($15/day)', 'Camp T-Shirt ($18)'],
    times: ['8:00 AM (Drop-off)', '9:00 AM (Drop-off)'],
  },
  {
    id: 'pno',
    label: "Parents' Night Out",
    imgUrl: '/booking/parentsnightout.jpg',
    photoUrl: '/booking/parentsnightout.jpg',
    desc: 'Saturday evening drop-off care for kids',
    color: 'var(--dt-sky)',
    colorHex: '#38bdf8',
    bgClass: 'bg-[#F0F9FF]',
    options: [
      {
        slug: 'standard',
        label: 'Standard',
        price: '$50',
        unit: 'per child',
        desc: 'Supervised play, dinner window, and themed evening activities.',
        inclusions: ['3-hour supervised care', 'Guided activities', 'Wind-down time'],
      },
      {
        slug: 'sibling-rate',
        label: 'Sibling Rate',
        price: '$40',
        unit: 'per sibling',
        desc: 'Discounted pricing when booking multiple children for the same evening.',
        inclusions: ['Same program', 'Shared family check-in', 'Sibling discount'],
      },
    ],
    addons: ['Dinner Included ($12)', 'Craft Activity ($8)', 'Movie Night Add-on ($5)'],
    times: ['4:00 PM'],
  },
  {
    id: 'field-trips',
    label: 'Field Trips',
    imgUrl: '/booking/fieldtrips.jpeg',
    photoUrl: '/booking/fieldtrips.jpeg',
    desc: 'Educational group outings for schools & daycares',
    color: 'var(--dt-amber)',
    colorHex: '#f59e0b',
    bgClass: 'bg-[#FFFBEB]',
    options: [
      {
        slug: 'preschool',
        label: 'Preschool Group',
        price: '$10',
        unit: 'per child',
        desc: 'Guided movement, sensory play, and age-appropriate exploration.',
        inclusions: ['Structured stations', 'Group orientation', 'Staff-facilitated'],
      },
      {
        slug: 'elementary',
        label: 'Elementary Group',
        price: '$12',
        unit: 'per child',
        desc: 'Teamwork games and collaborative challenges for older kids.',
        inclusions: ['Themed activity blocks', 'Rotation schedule', 'Leader briefing'],
      },
      {
        slug: 'daycare',
        label: 'Daycare Group',
        price: '$10',
        unit: 'per child',
        desc: 'Flexible weekday package designed for recurring partner visits.',
        inclusions: ['Flexible scheduling', 'Age-banded flow', 'Group host assistance'],
      },
      {
        slug: 'community',
        label: 'Community Group',
        price: '$11',
        unit: 'per child',
        desc: 'Youth organizations and community programs planning large outings.',
        inclusions: ['Large-group coordination', 'Program setup', 'Dedicated check-in'],
      },
    ],
    addons: ['Lunch Packages ($8/child)', 'Activity Workbook ($5/child)', 'Guided Tour ($50 flat)'],
    times: ['9:00 AM', '10:00 AM', '11:00 AM'],
  },
  {
    id: 'we-bring',
    label: 'Party at your place',
    imgUrl: '/booking/webring.jpeg',
    photoUrl: '/booking/webring.jpeg',
    desc: 'We bring the fun directly to your location',
    color: 'var(--dt-coral)',
    colorHex: '#f96060',
    bgClass: 'bg-[#FFF1F1]',
    options: [
      {
        slug: 'inflatables',
        label: 'Inflatables Package',
        price: '$399',
        unit: 'starting',
        desc: 'Core mobile party with inflatable setup and supervised activity flow.',
        inclusions: ['Delivery + setup', 'Inflatable equipment', 'Safety orientation'],
      },
      {
        slug: 'full-party',
        label: 'Full Party Package',
        price: '$749',
        unit: 'starting',
        desc: 'Activities, entertainment support, and premium party flow.',
        inclusions: ['Inflatables + stations', 'On-site support team', 'Setup + teardown'],
        badge: 'Most Popular',
      },
      {
        slug: 'corporate',
        label: 'Corporate Family Day',
        price: '$1,199',
        unit: 'starting',
        desc: 'Large-format package for employee events and branded activations.',
        inclusions: ['Large-event capacity', 'Custom layout planning', 'Operations support'],
      },
      {
        slug: 'custom',
        label: 'Custom Event',
        price: 'Custom',
        unit: 'quote based',
        desc: 'Tailored package for unique venues, themes, and requirements.',
        inclusions: ['Custom consultation', 'Flexible scope', 'Dedicated planner'],
      },
    ],
    addons: ['Generator Rental ($75)', 'Staff Supervision (+$50/hr)', 'Setup & Teardown ($100)'],
    times: ['10:00 AM', '12:00 PM', '2:00 PM', '4:00 PM'],
  },
  {
    id: 'events',
    label: 'Events & Parties',
    imgUrl: '/booking/eventsandparties.jpeg',
    photoUrl: '/booking/eventsandparties.jpeg',
    desc: 'Book a party room or whole-venue buyout',
    color: 'var(--dt-primary)',
    colorHex: '#1d7fe5',
    bgClass: 'bg-[#EFF6FF]',
    options: [
      {
        slug: 'private-room-silver',
        label: 'Silver Party Room',
        price: '$299',
        unit: 'starting',
        desc: 'Dedicated party room for up to 15 guests with open play access.',
        inclusions: ['1 party room (2hrs)', 'Open play for guests', 'Basic setup'],
      },
      {
        slug: 'private-room-gold',
        label: 'Gold Party Room',
        price: '$449',
        unit: 'starting',
        desc: 'Larger party room for up to 25 guests with premium setup.',
        inclusions: ['1 party room (2hrs)', 'Premium decorations', 'Photo station'],
        badge: 'Most Popular',
      },
      {
        slug: 'private-room-platinum',
        label: 'Platinum Party Room',
        price: '$649',
        unit: 'starting',
        desc: 'VIP experience with dual rooms and dedicated party coordinator.',
        inclusions: ['2 party rooms (2hrs)', 'Custom theme setup', 'Coordinator + staff'],
      },
      {
        slug: 'venue-buyout-standard',
        label: 'Whole Venue – Standard',
        price: '$899',
        unit: 'starting',
        desc: 'Complete exclusive access for uninterrupted celebrations.',
        inclusions: ['Full venue access', 'Dedicated team', 'Flexible layout'],
      },
      {
        slug: 'venue-buyout-premium',
        label: 'Whole Venue – Premium',
        price: '$1,499',
        unit: 'starting',
        desc: 'Full buyout with premium catering and AV package included.',
        inclusions: ['Full venue access', 'Catering package', 'AV & entertainment'],
        badge: 'Most Exclusive',
      },
    ],
    addons: [
      'Catering package ($150)',
      'Balloon garland ($75)',
      'DJ / music ($100)',
      'Photo booth ($120)',
      'Custom cake ($65)',
      'Extra party time ($75/hr)',
      'Character visit ($125)',
      'Goody bags ($8/child)',
    ],
    times: ['10:00 AM', '12:00 PM', '2:00 PM', '4:00 PM', '6:00 PM'],
  },
  {
    id: 'gym',
    label: 'Gym Classes',
    imgUrl: '/booking/gymclasses.jpeg',
    photoUrl: '/booking/gymclasses.jpeg',
    desc: 'Fitness classes for every age & ability',
    color: 'var(--dt-teal)',
    colorHex: '#00c49a',
    bgClass: 'bg-[#F0FDFB]',
    options: [
      {
        slug: 'single-class',
        label: 'Single Class',
        price: '$18',
        unit: 'per session',
        desc: 'Drop in for any single class that fits your schedule.',
        inclusions: ['1 class session', 'Equipment provided', 'Any age group'],
      },
      {
        slug: 'class-pack-5',
        label: '5-Class Pack',
        price: '$80',
        unit: '5 sessions',
        desc: 'Flexible pack valid for any class across any age group.',
        inclusions: ['5 class sessions', 'No expiry', 'Mix and match classes'],
        badge: 'Best Value',
      },
      {
        slug: 'monthly-unlimited',
        label: 'Monthly Unlimited',
        price: '$65',
        unit: 'per month',
        desc: 'Unlimited classes every month — the most cost-effective option.',
        inclusions: ['Unlimited classes', 'Priority booking', 'Member events access'],
      },
      {
        slug: 'family-pack',
        label: 'Family Pack',
        price: '$120',
        unit: 'per month',
        desc: 'Unlimited access for the whole family.',
        inclusions: ['Up to 4 family members', 'All age groups', 'Priority booking'],
      },
    ],
    addons: ['Personal Trainer ($35/session)', 'Nutrition Consult ($25)', 'Gym Towel Bundle ($15)'],
    times: ['7:00 AM', '9:00 AM', '10:30 AM', '12:00 PM', '4:00 PM', '5:30 PM', '7:00 PM'],
  },
  {
    id: 'learn',
    label: 'Learn Programs',
    imgUrl: '/booking/learnprograms.jpeg',
    photoUrl: '/booking/learnPrograms.jpeg',
    desc: 'Tutoring, test prep & enrichment programs',
    color: 'var(--dt-learn-green)',
    colorHex: '#0ca678',
    bgClass: 'bg-[#F0FDF4]',
    options: [
      {
        slug: 'core-academic',
        label: 'Core Academic Tutoring',
        price: '$55',
        unit: 'per hour',
        desc: 'One-on-one tutoring in Math, English, Reading, and Science.',
        inclusions: ['1-on-1 sessions', 'Progress tracking', 'Homework help'],
      },
      {
        slug: 'test-prep',
        label: 'Test Prep Package',
        price: '$299',
        unit: '6 sessions',
        desc: 'Structured prep for SAT, ACT, ISEE, SSAT, and AP exams.',
        inclusions: ['6 focused sessions', 'Practice tests', 'Strategy coaching'],
        badge: 'Most Popular',
      },
      {
        slug: 'enrichment',
        label: 'Enrichment Program',
        price: '$189',
        unit: 'per month',
        desc: 'STEM, coding, chess, public speaking and creative arts programs.',
        inclusions: ['Group sessions', 'Monthly activity kit', 'Progress report'],
      },
      {
        slug: 'summer-academy',
        label: 'Summer Academy',
        price: '$349',
        unit: 'per week',
        desc: 'Intensive summer learning with academics and enrichment activities.',
        inclusions: ['Full-day programming', 'Lunch included', 'End-of-week showcase'],
      },
    ],
    addons: ['Workbook Bundle ($25)', 'Progress Report Card ($10)', 'Parent Coach Session ($45)'],
    times: ['9:00 AM', '10:30 AM', '12:00 PM', '2:00 PM', '4:00 PM', '5:30 PM'],
  },
  {
    id: 'gifts',
    label: 'Gift Orders',
    imgUrl: '/booking/giftorders.jpeg',
    photoUrl: '/booking/giftorders.jpeg',
    desc: 'Curated gift baskets and care packages',
    color: 'var(--dt-coral)',
    colorHex: '#f96060',
    bgClass: 'bg-[var(--dt-coral-light)]',
    options: [
      {
        slug: 'gourmet-basket',
        label: 'Gourmet Gift Basket',
        price: '$65',
        unit: 'per basket',
        desc: 'Artisan snacks, premium treats, and locally sourced goodies.',
        inclusions: ['Handcrafted box', 'Personalized note', 'Local delivery'],
      },
      {
        slug: 'activity-kit',
        label: 'Activity Kit',
        price: '$45',
        unit: 'per kit',
        desc: 'DIY craft and play kits for kids aged 3–10.',
        inclusions: ['Age-appropriate kit', 'Instructions included', 'Premium packaging'],
        badge: 'Kids Favorite',
      },
      {
        slug: 'new-parent-box',
        label: 'New Parent Box',
        price: '$89',
        unit: 'per box',
        desc: 'Thoughtful essentials and treats curated for new parents.',
        inclusions: ['Baby essentials', 'Parent self-care items', 'Welcome card'],
      },
      {
        slug: 'custom-gift',
        label: 'Custom Gift Package',
        price: 'Custom',
        unit: 'quote based',
        desc: 'Fully bespoke gift curation for any budget and occasion.',
        inclusions: ['Personal shopping', 'Custom packaging', 'Priority delivery'],
      },
    ],
    addons: ['Gift Wrapping ($12)', 'Same-Day Delivery ($15)', 'Custom Card ($5)', 'Balloon Bundle ($18)'],
    times: ['9:00 AM Order Cut-off (Same Day)', '12:00 PM Order Cut-off (Afternoon Delivery)'],
  },
  {
    id: 'rentals',
    label: 'Equipment Rentals',
    imgUrl: '/booking/equipmentrental.jpeg',
    photoUrl: '/booking/equipmentrental.jpeg',
    desc: 'Bounce houses, photo booths, AV & more',
    color: 'var(--dt-coral)',
    colorHex: '#f96060',
    bgClass: 'bg-[var(--dt-coral-light)]',
    options: [
      {
        slug: 'inflatable-rental',
        label: 'Inflatable Rental',
        price: '$199',
        unit: 'per day',
        desc: 'Bounce houses and inflatable slides for parties and events.',
        inclusions: ['Delivery + setup', 'Safety mat included', 'Full-day rental'],
      },
      {
        slug: 'photo-booth',
        label: 'Photo Booth Rental',
        price: '$249',
        unit: 'per event',
        desc: 'Full-featured photo booth with props and instant prints.',
        inclusions: ['Booth + props', 'Digital copies', 'Attendant included'],
        badge: 'Most Popular',
      },
      {
        slug: 'av-package',
        label: 'AV Package',
        price: '$149',
        unit: 'per day',
        desc: 'Sound system, microphone, projector and screen.',
        inclusions: ['Speaker system', 'Microphone', 'Projector + screen'],
      },
      {
        slug: 'concession-pack',
        label: 'Concession Package',
        price: '$99',
        unit: 'per event',
        desc: 'Popcorn machine, snow cone maker, and cotton candy station.',
        inclusions: ['3 machines', 'Supplies included', 'Setup + support'],
      },
    ],
    addons: ['Staff Supervision ($50/hr)', 'Extra Hour ($75)', 'Setup & Teardown ($100)', 'Generator ($75)'],
    times: ['9:00 AM', '12:00 PM', '3:00 PM'],
  },
]

export const BOOKING_STEPS = ['Service', 'Package', 'Date & Time', 'Guests', 'Review']

export const AGE_OPTIONS = [
  'Infant (0–1)',
  'Toddler (2–3)',
  'Preschool (4–5)',
  'School age (6–10)',
  'Adult',
]
