export const QUERY_KEYS = {
  AUTH: {
    SESSION: ['auth', 'session'] as const,
    ME: ['auth', 'me'] as const,
  },
  ADMIN: {
    ROLES: {
      LIST: (filters?: object) => ['admin', 'roles', filters] as const,
      ROLE: (id: string) => ['admin', 'roles', id] as const,
      MY_PERMISSIONS: ['admin', 'roles', 'me', 'permissions'] as const,
    },
    SCHEDULING: {
      EVENTS: (filters?: object) => ['admin', 'events', filters] as const,
      EVENT: (id: string) => ['admin', 'events', id] as const,
      CALENDAR: (params?: object) => ['admin', 'calendar', params] as const,
      SLOTS: (filters?: object) => ['admin', 'scheduling', 'slots', filters] as const,
      SLOT: (id: string) => ['admin', 'scheduling', 'slots', id] as const,
      ROSTER: (slotId: string) => ['admin', 'scheduling', 'slots', slotId, 'roster'] as const,
      WAITLIST: (slotId: string) => ['admin', 'scheduling', 'slots', slotId, 'waitlist'] as const,
      BOOKINGS: (filters?: object) => ['admin', 'scheduling', 'bookings', filters] as const,
      SERVICES: (filters?: object) => ['admin', 'scheduling', 'services', filters] as const,
      CATEGORIES: ['admin', 'scheduling', 'service-categories'] as const,
      LOCATIONS: ['admin', 'locations'] as const,
      ADD_ONS: (filters?: object) => ['admin', 'add-ons', filters] as const,
      STAFF_AVAILABILITY: (staffId: string, startAt: string, endAt: string) =>
        ['admin', 'scheduling', 'staff-availability', staffId, startAt, endAt] as const,
    },
    CALENDAR: {
      AVAILABILITY_GRID: (locationId: string, from: string, to: string) =>
        ['admin', 'calendar', 'availability-grid', locationId, from, to] as const,
      PRIVATE_HIRE_REQUESTS: (filters?: object) => ['admin', 'calendar', 'private-hire', filters] as const,
      CONFLICTS: (locationId: string, startAt: string, endAt: string, excludeSlotId?: string) =>
        ['admin', 'calendar', 'conflicts', locationId, startAt, endAt, excludeSlotId ?? ''] as const,
    },
    CLIENTS: {
      FAMILIES: (filters?: object) => ['admin', 'families', filters] as const,
      FAMILY: (id: string) => ['admin', 'families', id] as const,
      TAGS: ['admin', 'tags'] as const,
      WAIVERS: ['admin', 'waivers'] as const,
      MEMBERSHIPS: ['admin', 'memberships'] as const,
      CLASS_PACKS: ['admin', 'class-packs'] as const,
      CONTACTS: (filters?: object) => ['admin', 'clients', 'contacts', filters] as const,
      CONTACT: (id: string) => ['admin', 'clients', 'contacts', id] as const,
      CONTACT_BOOKINGS: (id: string, filters?: object) => ['admin', 'clients', 'contacts', id, 'bookings', filters] as const,
      CONTACT_SPEND: (id: string) => ['admin', 'clients', 'contacts', id, 'spend'] as const,
      CONTACT_LEDGER: (id: string, filters?: object) => ['admin', 'clients', 'contacts', id, 'ledger', filters] as const,
      DOCUMENTS: (filters?: object) => ['admin', 'clients', 'documents', filters] as const,
      DOCUMENT: (id: string) => ['admin', 'clients', 'documents', id] as const,
      PLANS: (filters?: object) => ['admin', 'clients', 'plans', filters] as const,
      PACK_DEFINITIONS: (filters?: object) => ['admin', 'clients', 'credit-packs', filters] as const,
      CONTACT_PACKS: (id: string) => ['admin', 'clients', 'contacts', id, 'packs'] as const,
    },
    REPORTS: {
      DASHBOARD: (params?: object) => ['admin', 'reports', 'dashboard', params] as const,
      REVENUE: (params?: object) => ['admin', 'reports', 'revenue', params] as const,
      CLIENTS: (params?: object) => ['admin', 'reports', 'clients', params] as const,
      INVOICES: (filters?: object) => ['admin', 'invoices', filters] as const,
    },
    LEADS: {
      LIST: (filters?: object) => ['admin', 'leads', filters] as const,
      LEAD: (id: string) => ['admin', 'leads', id] as const,
      SMART_LISTS: ['admin', 'smart-lists'] as const,
      TEMPLATES: ['admin', 'templates'] as const,
    },
    STAFF: {
      LIST: (filters?: object) => ['admin', 'staff', filters] as const,
      MEMBER: (id: string) => ['admin', 'staff', id] as const,
      PAYROLL: (periodId: string) => ['admin', 'payroll', periodId] as const,
      TIME_CLOCK: (staffId: string, period?: string) => ['admin', 'time-clock', staffId, period] as const,
    },
    INVENTORY: {
      PRODUCTS: (filters?: object) => ['admin', 'products', filters] as const,
      PRODUCT: (id: string) => ['admin', 'products', id] as const,
      ORDERS: (filters?: object) => ['admin', 'orders', filters] as const,
      COUPONS: ['admin', 'coupons'] as const,
    },
  },
  USER: {
    BOOKING: (id: string) => ['user', 'bookings', id] as const,
    BOOKINGS: (filters?: object) => ['user', 'bookings', filters] as const,
    ACCOUNT: ['user', 'account'] as const,
    MY_PROFILE: ['user', 'account', 'profile'] as const,
    MY_FAMILY: ['user', 'account', 'family'] as const,
    MY_DOCUMENTS: ['user', 'account', 'documents'] as const,
    MY_SUBSCRIPTION: ['user', 'account', 'subscription'] as const,
    AVAILABLE_PLANS: ['user', 'account', 'available-plans'] as const,
    MY_CREDITS: ['user', 'account', 'credits'] as const,
    MY_CREDIT_LEDGER: (filters?: object) => ['user', 'account', 'credit-ledger', filters] as const,
    AVAILABLE_PACKS: ['user', 'account', 'available-packs'] as const,
    EVENTS_PARTY_PAGE: ['user', 'events', 'party-page'] as const,
    SCHEDULING: {
      PUBLIC_SLOTS: (filters?: object) => ['public', 'slots', filters] as const,
      PUBLIC_SLOT: (id: string) => ['public', 'slots', id] as const,
      PUBLIC_SERVICES: (filters?: object) => ['public', 'services', filters] as const,
      PUBLIC_SERVICE_CATEGORIES: ['public', 'service-categories'] as const,
      PUBLIC_LOCATIONS: ['public', 'locations'] as const,
      OPEN_AVAILABILITY: (serviceId: string, date: string) => ['public', 'open-availability', serviceId, date] as const,
      MY_BOOKINGS: (filters?: object) => ['user', 'my-bookings', filters] as const,
      MY_BOOKING: (id: string) => ['user', 'my-bookings', id] as const,
      MY_UPCOMING: ['user', 'upcoming'] as const,
      PRIVATE_HIRE_AVAILABILITY: (locationId: string, from: string, to: string) =>
        ['user', 'private-hire', 'availability', locationId, from, to] as const,
    },
  },
} as const

