export const ROUTES = {
  USER: {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
    VERIFY_EMAIL: '/verify-email',
    BOOK: '/book',
    PLAY: '/play',
    CAFE: '/cafeAndfood',
    EVENTS: '/events',
    GYM: '/gym',
    LEARN: '/learn',
    RENTALS: '/rentals',
    GIFTS: '/gifts',
    SHOP: '/shop',
    CHECKOUT: '/checkout',
    CONTACT: '/contact',
    MY_ACCOUNT: '/my-account',
    BOOKING: (id: string) => `/booking/${id}`,
    ACTIVITIES: '/activities',
    ACTIVITY_CATEGORY: (serviceType: string) => `/activities/${serviceType}`,
    ACTIVITY_DETAIL: (serviceType: string, slotId: string) => `/activities/${serviceType}/${slotId}`,
    ACTIVITY_OPEN_BOOK: (serviceType: string, serviceId: string) => `/activities/${serviceType}/${serviceId}/book`,
    BOOKING_CONFIRM: '/booking/confirm',
    BOOKING_SUCCESS: '/booking/success',
    MY_BOOKINGS: '/my-account/bookings',
    MY_BOOKING_DETAIL: (id: string) => `/my-account/bookings/${id}`,
  },
  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    BOOKINGS: '/admin/bookings',
    USERS: '/admin/users',
    SERVICES: '/admin/services',
    SETTINGS: '/admin/settings',
    ONBOARDING: '/admin/onboarding',
    SCHEDULING: '/admin/scheduling',
    SCHEDULING_EVENT: (id: string) => `/admin/scheduling/${id}`,
    SCHEDULING_NEW: '/admin/scheduling/new',
    SCHEDULING_CALENDAR: '/admin/scheduling/calendar',
    SCHEDULING_LOCATIONS: '/admin/scheduling/locations',
    SCHEDULING_SERVICES: '/admin/scheduling/services',
    SCHEDULING_ADD_ONS: '/admin/scheduling/add-ons',
    CLIENTS: '/admin/clients',
    CLIENT: (id: string) => `/admin/clients/${id}`,
    CLIENTS_NEW: '/admin/clients/new',
    CLIENTS_WAIVERS: '/admin/clients/waivers',
    CLIENTS_MEMBERSHIPS: '/admin/clients/memberships',
    CLIENTS_CLASS_PACKS: '/admin/clients/class-packs',
    CLIENTS_TAGS: '/admin/clients/tags',
    REPORTS: '/admin/reports',
    REPORTS_REVENUE: '/admin/reports/revenue',
    REPORTS_CLIENTS: '/admin/reports/clients',
    REPORTS_INVOICES: '/admin/reports/invoices',
    LEADS: '/admin/leads',
    LEAD: (id: string) => `/admin/leads/${id}`,
    LEADS_SMART_LISTS: '/admin/leads/smart-lists',
    LEADS_TEMPLATES: '/admin/leads/templates',
    LEADS_CAMPAIGNS: '/admin/leads/campaigns',
    STAFF: '/admin/staff',
    STAFF_MEMBER: (id: string) => `/admin/staff/${id}`,
    STAFF_TIME_CLOCK: '/admin/staff/time-clock',
    STAFF_PAYROLL: '/admin/staff/payroll',
    STAFF_LEAVE: '/admin/staff/leave',
    INVENTORY: '/admin/inventory',
    INVENTORY_PRODUCTS: '/admin/inventory/products',
    INVENTORY_PRODUCT: (id: string) => `/admin/inventory/products/${id}`,
    INVENTORY_ORDERS: '/admin/inventory/orders',
    INVENTORY_COUPONS: '/admin/inventory/coupons',
    INVENTORY_POS: '/admin/inventory/pos',
    INTEGRATIONS: '/admin/integrations',
    INTEGRATIONS_NOTIFICATIONS: '/admin/integrations/notifications',
    ROLES: '/admin/roles',
    ROLES_NEW: '/admin/roles/new',
    ROLE: (id: string) => `/admin/roles/${id}`,
  },
} as const

