import type { FilterTag, HeroPill, NavSectionItem, ShopSectionMeta } from './types'

export const NAV_SECTIONS: NavSectionItem[] = [
  { id: 'toys', label: 'Toys' },
  { id: 'clothes', label: 'Clothes' },
  { id: 'furniture', label: 'Furniture' },
  { id: 'branded', label: 'DT Branded' },
]

// ─── TOYS ─────────────────────────────────────────────────────────────────────
export const TOYS = [
  {
    name: 'Discovery Builder Set',
    desc: 'Open-ended wooden blocks in 40 shapes and natural finishes. Inspires architecture, storytelling, and spatial reasoning.',
    price: '$38',
    age: '2+',
    image: 'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=500&q=80',
    badge: 'Best Seller',
    color: 'var(--dt-coral)',
    bg: 'var(--dt-coral-soft)',
    border: '#FFD0D0',
  },
  {
    name: 'Sensory Bin Starter Kit',
    desc: 'Everything to build a rich sensory bin at home — bin, kinetic sand, scoops, molds, and mini figurines.',
    price: '$29',
    age: '18mo+',
    image: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=500&q=80',
    badge: 'New',
    color: '#0CA678',
    bg: 'var(--dt-mint-soft)',
    border: '#96F2D7',
  },
  {
    name: 'Magnetic Tile Set (60 pcs)',
    desc: 'Colorful magnetic tiles for infinite building possibilities. STEM-certified, BPA-free, and compatible with major brands.',
    price: '$54',
    age: '3+',
    image: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=500&q=80',
    badge: 'Best Seller',
    color: '#4C6EF5',
    bg: '#F0F4FF',
    border: '#C5D0FF',
  },
  {
    name: 'Junior Science Kit',
    desc: 'Grow crystals, make slime, and conduct 12 safe experiments at home. Includes lab coat, goggles, and full instructions.',
    price: '$42',
    age: '5+',
    image: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=500&q=80',
    badge: null,
    color: '#7950F2',
    bg: '#F3F0FF',
    border: '#D0BFFF',
  },
  {
    name: 'Pretend Play Kitchen Set',
    desc: 'Wooden play kitchen with 20+ food accessories, pots, pans, and utensils. Durable and beautifully crafted.',
    price: '$68',
    age: '2+',
    image: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=500&q=80',
    badge: null,
    color: '#D97706',
    bg: '#FFFBEB',
    border: '#FDE68A',
  },
  {
    name: 'Puzzle Collection (3-pack)',
    desc: 'Set of three age-appropriate floor puzzles — animals, world map, and solar system. 24–48 pieces each.',
    price: '$32',
    age: '3+',
    image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=500&q=80',
    badge: 'Sale',
    color: 'var(--dt-coral)',
    bg: 'var(--dt-coral-soft)',
    border: '#FFD0D0',
    originalPrice: '$42',
  },
  {
    name: 'Art & Craft Mega Box',
    desc: 'Over 150 art supplies — washable paints, markers, stickers, foam, pom-poms, and project cards for weeks of creativity.',
    price: '$46',
    age: '4+',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=500&q=80',
    badge: 'Best Seller',
    color: '#0CA678',
    bg: 'var(--dt-mint-soft)',
    border: '#96F2D7',
  },
  {
    name: 'Stomp Rocket Launcher',
    desc: 'Launch foam rockets up to 200 feet using air power — no batteries required. Safe, reusable, and endlessly fun outdoors.',
    price: '$24',
    age: '5+',
    image: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=500&q=80',
    badge: 'New',
    color: '#4C6EF5',
    bg: '#F0F4FF',
    border: '#C5D0FF',
  },
  {
    name: 'Puppet Theatre + 6 Puppets',
    desc: 'Freestanding puppet theatre with six hand puppets. Encourages storytelling, language development, and dramatic play.',
    price: '$55',
    age: '3+',
    image: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=500&q=80',
    badge: null,
    color: '#7950F2',
    bg: '#F3F0FF',
    border: '#D0BFFF',
  },
]

// ─── CLOTHES ──────────────────────────────────────────────────────────────────
export const CLOTHES = [
  {
    name: 'Adventure Graphic Tee',
    desc: '"Explorer in Training" and "Little Discoverer" screen-printed tees in soft 100% cotton. Machine washable.',
    price: '$18 – $22',
    sizes: 'Sizes 2T – 10',
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=500&q=80',
    badge: 'Best Seller',
    color: '#4C6EF5',
    bg: '#F0F4FF',
    border: '#C5D0FF',
  },
  {
    name: 'Discovery Town Hoodie',
    desc: 'Cozy pullover hoodie with the DiscoveryTown logo on the chest. Fleece-lined, perfect for cooler play days.',
    price: '$34 – $40',
    sizes: 'Sizes 2T – 12',
    image: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=500&q=80',
    badge: null,
    color: 'var(--dt-coral)',
    bg: 'var(--dt-coral-soft)',
    border: '#FFD0D0',
  },
  {
    name: 'Play-Ready Jogger Set',
    desc: 'Stretchy, breathable jogger + matching long-sleeve top. Designed for active play, tumbling, and gym days.',
    price: '$38 – $46',
    sizes: 'Sizes 18mo – 8',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&q=80',
    badge: 'New',
    color: '#0CA678',
    bg: 'var(--dt-mint-soft)',
    border: '#96F2D7',
  },
  {
    name: 'Grip Socks (3-Pack)',
    desc: 'Non-slip socks required for the play café — fun patterns, rubber grip bottoms, and super soft. Essential for every visit.',
    price: '$12',
    sizes: 'S / M / L (Kids)',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&q=80',
    badge: 'Must-Have',
    color: '#D97706',
    bg: '#FFFBEB',
    border: '#FDE68A',
  },
  {
    name: 'Little Chef Apron & Hat Set',
    desc: "Adjustable kids' apron with matching chef hat. Perfect for cooking classes and kitchen play at home.",
    price: '$22',
    sizes: 'One size fits 3–10',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=500&q=80',
    badge: null,
    color: '#7950F2',
    bg: '#F3F0FF',
    border: '#D0BFFF',
  },
  {
    name: 'Ninja Warrior Training Tee',
    desc: '"Warrior in Training" performance tee — moisture-wicking, lightweight, and perfect for gym and obstacle classes.',
    price: '$20 – $24',
    sizes: 'Sizes 4 – 12',
    image: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=500&q=80',
    badge: null,
    color: 'var(--dt-coral)',
    bg: 'var(--dt-coral-soft)',
    border: '#FFD0D0',
  },
  {
    name: 'Parent Comfort Tee',
    desc: 'Soft, relaxed "DiscoveryTown Parent" graphic tee for adults. Because you deserve matching swag too.',
    price: '$26',
    sizes: 'Unisex S – 2XL',
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500&q=80',
    badge: 'New',
    color: '#4C6EF5',
    bg: '#F0F4FF',
    border: '#C5D0FF',
  },
  {
    name: 'Cozy Zip Onesie',
    desc: 'Ultra-soft zip-up onesie for babies and toddlers. Perfect for play café crawling and climbing.',
    price: '$28 – $32',
    sizes: 'Sizes 3mo – 24mo',
    image: 'https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=500&q=80',
    badge: null,
    color: '#0CA678',
    bg: 'var(--dt-mint-soft)',
    border: '#96F2D7',
  },
]

// ─── FURNITURE ────────────────────────────────────────────────────────────────
export const FURNITURE = [
  {
    name: 'Montessori Reading Nook',
    desc: 'Solid wood floor-level bookshelf with a padded cushion seat built in. Encourages independent reading habits in children.',
    price: '$185 – $225',
    image: 'https://images.unsplash.com/photo-1444021465936-c6ca81d39b84?w=500&q=80',
    badge: 'Best Seller',
    material: 'Solid pine, non-toxic finish',
    color: '#D97706',
    bg: '#FFFBEB',
    border: '#FDE68A',
  },
  {
    name: "Kids' Activity Table & 2 Chairs",
    desc: 'Height-adjustable table with two matching chairs and a built-in storage bin underneath. Perfect for art, puzzles, and STEM.',
    price: '$145 – $175',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&q=80',
    badge: null,
    material: 'Birch plywood, powder-coated legs',
    color: 'var(--dt-coral)',
    bg: 'var(--dt-coral-soft)',
    border: '#FFD0D0',
  },
  {
    name: 'Climbing Triangle (Pikler)',
    desc: 'Classic Pikler triangle for indoor climbing, balance, and gross motor development. Folds flat for easy storage.',
    price: '$165 – $210',
    image: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=500&q=80',
    badge: 'New',
    material: 'Birch wood, sanded smooth, no sharp edges',
    color: '#0CA678',
    bg: 'var(--dt-mint-soft)',
    border: '#96F2D7',
  },
  {
    name: 'Teepee Play Tent',
    desc: 'Cotton canvas teepee with a window, floor mat, and string lights included. Creates an instant cozy imagination space.',
    price: '$88 – $115',
    image: 'https://images.unsplash.com/photo-1544457070-4cd773b4d71e?w=500&q=80',
    badge: 'Popular',
    material: 'Cotton canvas, pine poles',
    color: '#7950F2',
    bg: '#F3F0FF',
    border: '#D0BFFF',
  },
  {
    name: 'Toy Storage Cubby (6-Bin)',
    desc: 'Six-compartment open cubby with colorful fabric bins. Easy for children to independently sort and access their toys.',
    price: '$128 – $155',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&q=80',
    badge: null,
    material: 'MDF frame, fabric bins',
    color: '#4C6EF5',
    bg: '#F0F4FF',
    border: '#C5D0FF',
  },
  {
    name: 'Foam Play Mat (6-Tile Set)',
    desc: 'Interlocking foam floor tiles — soft, waterproof, and easy to clean. Protects little ones during floor play and tumbling.',
    price: '$52 – $68',
    image: 'https://images.unsplash.com/photo-1549488344-c7da79ec15e0?w=500&q=80',
    badge: 'Best Seller',
    material: 'EVA foam, non-toxic',
    color: 'var(--dt-coral)',
    bg: 'var(--dt-coral-soft)',
    border: '#FFD0D0',
  },
  {
    name: 'Art Easel (Double-Sided)',
    desc: 'Adjustable height easel with chalkboard on one side and whiteboard on the other. Includes a paper roll holder and supply tray.',
    price: '$75 – $95',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=500&q=80',
    badge: null,
    material: 'Solid beech wood',
    color: '#D97706',
    bg: '#FFFBEB',
    border: '#FDE68A',
  },
  {
    name: 'Balance Board',
    desc: 'Solid wood rocker balance board for core strength, coordination, and sensory play. Safe for ages 2 and up.',
    price: '$58 – $75',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&q=80',
    badge: 'New',
    material: 'Birch plywood, non-slip base',
    color: '#0CA678',
    bg: 'var(--dt-mint-soft)',
    border: '#96F2D7',
  },
]

// ─── BRANDED ──────────────────────────────────────────────────────────────────
export const BRANDED = [
  {
    name: 'DT Logo Tumbler (20oz)',
    desc: 'Double-wall insulated tumbler with the DiscoveryTown logo. Keeps drinks hot for 6 hrs, cold for 12.',
    price: '$28',
    image: 'https://images.unsplash.com/photo-1523381294911-8d3cead13475?w=500&q=80',
    badge: 'Best Seller',
    color: 'var(--dt-coral)',
    bg: 'var(--dt-coral-soft)',
    border: '#FFD0D0',
  },
  {
    name: 'Discovery Town Tote Bag',
    desc: 'Heavy-duty canvas tote with the DT logo. Perfect for carrying snacks, gear, or groceries.',
    price: '$18',
    image: 'https://images.unsplash.com/photo-1553531091-c3e81aca0494?w=500&q=80',
    badge: null,
    color: '#4C6EF5',
    bg: '#F0F4FF',
    border: '#C5D0FF',
  },
  {
    name: 'DT Branded Cap',
    desc: 'Adjustable embroidered cap in navy or sand. Adult one-size-fits-most.',
    price: '$24',
    image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=500&q=80',
    badge: 'New',
    color: '#D97706',
    bg: '#FFFBEB',
    border: '#FDE68A',
  },
  {
    name: "Kids' Backpack",
    desc: 'Mini backpack with the DT logo patch, padded straps, and front zipper pocket. Perfect for gym & play days.',
    price: '$32',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&q=80',
    badge: 'Best Seller',
    color: '#0CA678',
    bg: 'var(--dt-mint-soft)',
    border: '#96F2D7',
  },
  {
    name: 'Sticker Sheet Pack',
    desc: 'Three sheets of DiscoveryTown character and explorer stickers — great for water bottles, notebooks, and lunchboxes.',
    price: '$6',
    image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=500&q=80',
    badge: null,
    color: '#7950F2',
    bg: '#F3F0FF',
    border: '#D0BFFF',
  },
  {
    name: 'DT Branded Mug (12oz)',
    desc: 'Ceramic mug with the DiscoveryTown logo. Microwave and dishwasher safe. A café staple at home.',
    price: '$16',
    image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=500&q=80',
    badge: null,
    color: 'var(--dt-coral)',
    bg: 'var(--dt-coral-soft)',
    border: '#FFD0D0',
  },
  {
    name: "Explorer's Journal",
    desc: 'Hardcover lined journal with "Young Explorer" embossed on the cover. 200 pages, lay-flat binding.',
    price: '$14',
    image: 'https://images.unsplash.com/photo-1455390582262-044cdead27d8?w=500&q=80',
    badge: null,
    color: '#D97706',
    bg: '#FFFBEB',
    border: '#FDE68A',
  },
  {
    name: 'Gift Card',
    desc: 'Give the gift of discovery! Available in $25, $50, $100, and custom amounts. Redeemable for any DT service.',
    price: 'From $25',
    image: 'https://images.unsplash.com/photo-1512418490979-92798cec1380?w=500&q=80',
    badge: 'Perfect Gift',
    color: '#4C6EF5',
    bg: '#F0F4FF',
    border: '#C5D0FF',
  },
]

export const FILTER_TAGS: FilterTag[] = ['All', 'New', 'Best Seller', 'Sale']

export const HERO_PILLS: HeroPill[] = [
  { label: '🧸 Toys', bg: 'var(--dt-coral-soft)', text: 'var(--dt-coral)', border: '#FFD0D0' },
  { label: '👕 Clothes', bg: 'var(--dt-mint-soft)', text: '#0CA678', border: '#96F2D7' },
  { label: '🪑 Furniture', bg: '#FFFBEB', text: '#D97706', border: '#FDE68A' },
  { label: '🏷️ DT Branded', bg: '#F3F0FF', text: '#7950F2', border: '#D0BFFF' },
]

export const SHOP_SECTIONS: ShopSectionMeta[] = [
  {
    id: 'toys',
    eyebrow: 'Toys',
    title: 'Play That Means Something',
    desc: "Open-ended, screen-free, and thoughtfully chosen. Every toy in our shop is selected to spark creativity, build skills, and hold a child's attention for more than five minutes.",
    emptyText: 'No "{filter}" items in Toys right now.',
    items: TOYS,
    showAge: true,
  },
  {
    id: 'clothes',
    eyebrow: 'Clothes',
    title: 'Dressed for Discovery',
    desc: 'Soft, durable, and designed for active kids. From grip socks (required for the play cafe!) to cozy hoodies and performance tees for gym days.',
    emptyText: 'No "{filter}" items in Clothes right now.',
    items: CLOTHES,
    showSizes: true,
  },
  {
    id: 'furniture',
    eyebrow: 'Furniture',
    title: 'Spaces That Grow With Them',
    desc: 'Montessori-inspired, beautifully crafted furniture and play spaces for the home. Designed to encourage independence, creativity, and movement.',
    emptyText: 'No "{filter}" items in Furniture right now.',
    items: FURNITURE,
    showMaterial: true,
  },
  {
    id: 'branded',
    eyebrow: 'DT Branded Gear',
    title: 'Wear the Discovery',
    desc: 'DiscoveryTown mugs, totes, caps, stickers, journals, and gift cards - for fans of the space who want to take a piece of it home.',
    emptyText: 'No "{filter}" items in DT Branded right now.',
    items: BRANDED,
  },
]
